function TaskJacobian = g_ExtenalForce_Jacobian(in1)
%g_ExtenalForce_Jacobian
%    TaskJacobian = g_ExtenalForce_Jacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Jun-2024 16:37:13

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = sin(t2);
t4 = t3./4.0;
t5 = -t4;
TaskJacobian = [t5-sin(q1)./2.0,t5,0.0];
