function Task = g_ExtenalForce(in1)
%g_ExtenalForce
%    Task = g_ExtenalForce(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Jun-2024 16:37:13

q1 = in1(1,:);
q2 = in1(2,:);
Task = cos(q1+q2)./4.0+cos(q1)./2.0;
