function TaskJacobian_derivative = g_ExtenalForce_Jacobian_derivative(in1,in2)
%g_ExtenalForce_Jacobian_derivative
%    TaskJacobian_derivative = g_ExtenalForce_Jacobian_derivative(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Jun-2024 16:37:13

q1 = in1(1,:);
q2 = in1(2,:);
v1 = in2(1,:);
v2 = in2(2,:);
t2 = q1+q2;
t3 = cos(t2);
TaskJacobian_derivative = [-v1.*(t3./4.0+cos(q1)./2.0)-(t3.*v2)./4.0,t3.*(v1+v2).*(-1.0./4.0),0.0];
